# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: TS Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI: false

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - run: npm run test-ci
      - name: use ci badge
        uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: ee73fac1f1a5b3f749e43605128297cd
          token: ${{ secrets.ALGOLAND_TS_TEST }}
